<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AizenX</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <Version>2.2.1</Version>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CodeX.Core">
      <HintPath>BuildRefs\CodeX.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="CodeX.Games.RDR2">
      <HintPath>BuildRefs\CodeX.Games.RDR2.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>